### ISSUE TITLE
Dinosaur Sprites

### ISSUE THREAD

**Issue by AFCMS** [AFCMS/devpet#15]
@Klhmt

- [x] 48x48 pixels, with **at least** 1px margins on each side
- [x] Black on white background, black will light up on screen (inverted)
- [x] Base design
- [x] Anims (2-3 frames each)
   - [x] IDLE (potentially different ones for health? not priority)
   - [x] IDLE listening (maybe a headset or just music notes around?)
   - [x] Dead
   - [x] Wake up (when starting up the tamagotchi)
   - [x] Drink coffee
   - [x] Party (on notifications)
- [x] License infos
- [x] Credits to @Klhmt

**Comment by Klhmt** [comment]
I suppose the 1 pixel margins are counted in the 48 pixels dimension?

**Comment by AFCMS** [comment]
> I suppose the 1 pixel margins are counted in the 48 pixels dimension?

Yes
